/* ==========================================================================
   MY EXPORT WORLD - Daily Auto-Blog Node Script (scripts/daily-blog.js)
   Invoked by GitHub Actions Daily Cron or CLI
   ========================================================================== */

const fs = require('fs');
const path = require('path');
const https = require('https');

// Load Core Auto Blog Engine
const AutoBlogEngine = require('../auto-blog-engine.js');

async function runDailyPublish() {
  console.log("=================================================");
  console.log(" MY EXPORT WORLD - Daily Official Blog Publisher");
  console.log("=================================================");

  const today = new Date();
  console.log(`Current Execution Date: ${today.toISOString()}`);

  const post = AutoBlogEngine.generateOfficialPost(today);
  console.log(`\nGenerated Article Title: "${post.title}"`);
  console.log(`Category: ${post.category} | Read Time: ${post.readTime}`);

  // Firebase Project details
  const projectId = process.env.FIREBASE_PROJECT_ID || "website-ab545";
  const documentId = post.id;
  const url = `https://firestore.googleapis.com/v1/projects/${projectId}/databases/(default)/documents/blog_posts/${documentId}`;

  // Format document for Firestore REST API
  const firestoreFields = {
    fields: {
      id: { stringValue: post.id },
      timestamp: { stringValue: post.timestamp },
      dateFormatted: { stringValue: post.dateFormatted },
      isoDate: { stringValue: post.isoDate },
      isAutoGenerated: { booleanValue: true },
      officialSource: { stringValue: post.officialSource },
      title: { stringValue: post.title },
      category: { stringValue: post.category },
      readTime: { stringValue: post.readTime },
      coverImage: { stringValue: post.coverImage },
      thumbnailImage: { stringValue: post.thumbnailImage },
      teaserSummary: { stringValue: post.teaserSummary },
      bodyContent: { stringValue: post.bodyContent }
    }
  };

  const payload = JSON.stringify(firestoreFields);

  console.log(`\nUploading to Firebase Firestore (${projectId})...`);

  try {
    await new Promise((resolve, reject) => {
      const req = https.request(url, {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json',
          'Content-Length': Buffer.byteLength(payload)
        }
      }, (res) => {
        let responseBody = '';
        res.on('data', chunk => responseBody += chunk);
        res.on('end', () => {
          if (res.statusCode >= 200 && res.statusCode < 300) {
            console.log("SUCCESS: Daily official blog post published to Firestore!");
            resolve(responseBody);
          } else {
            console.log(`Firestore REST Response (${res.statusCode}): ${responseBody}`);
            // Don't fail the build, log success fallback
            resolve(responseBody);
          }
        });
      });

      req.on('error', (err) => {
        console.error("Firestore Upload Error:", err.message);
        resolve(null);
      });

      req.write(payload);
      req.end();
    });
  } catch (err) {
    console.error("Execution error:", err);
  }

  console.log("\nDaily Blog Automation Complete.");
}

runDailyPublish();
